// Generated from Supabase REST API schema - 2026-05-18T17:27:40.769Z
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      billing_invoices: {
        Row: {
      id: string
      hotel_id: string
      period_start: string
      period_end: string
      plan_fee: number
      ota_commissions: number
      upsell_commissions: number
      total: number
      status: string
      wompi_reference?: string
      wompi_transaction_id?: string
      created_at?: string
      paid_at?: string
      ota_commissions_total?: number
        };
        Insert: {
      id: string
      hotel_id: string
      period_start: string
      period_end: string
      plan_fee: number
      ota_commissions: number
      upsell_commissions: number
      total: number
      status: string
      wompi_reference?: string
      wompi_transaction_id?: string
      created_at?: string
      paid_at?: string
      ota_commissions_total?: number
        };
        Update: {
      id?: string
      hotel_id?: string
      period_start?: string
      period_end?: string
      plan_fee?: number
      ota_commissions?: number
      upsell_commissions?: number
      total?: number
      status?: string
      wompi_reference?: string
      wompi_transaction_id?: string
      created_at?: string
      paid_at?: string
      ota_commissions_total?: number
        };
        Relationships: [];
      };
      payments: {
        Row: {
      id: string
      created_at?: string
      booking_id: string
      amount: number
      method: string
      notes?: string
      staff_id?: string
        };
        Insert: {
      id: string
      created_at?: string
      booking_id: string
      amount: number
      method: string
      notes?: string
      staff_id?: string
        };
        Update: {
      id?: string
      created_at?: string
      booking_id?: string
      amount?: number
      method?: string
      notes?: string
      staff_id?: string
        };
        Relationships: [];
      };
      room_service_orders: {
        Row: {
      id: string
      created_at: string
      hotel_id: string
      room_id?: string
      items: Json
      total_price: number
      status?: string
        };
        Insert: {
      id: string
      created_at: string
      hotel_id: string
      room_id?: string
      items: Json
      total_price: number
      status?: string
        };
        Update: {
      id?: string
      created_at?: string
      hotel_id?: string
      room_id?: string
      items?: Json
      total_price?: number
      status?: string
        };
        Relationships: [];
      };
      tenant_payments: {
        Row: {
      id: string
      wompi_transaction_id: string
      reference: string
      amount_cop: number
      method?: string
      status: string
      created_at: string
        };
        Insert: {
      id: string
      wompi_transaction_id: string
      reference: string
      amount_cop: number
      method?: string
      status: string
      created_at: string
        };
        Update: {
      id?: string
      wompi_transaction_id?: string
      reference?: string
      amount_cop?: number
      method?: string
      status?: string
      created_at?: string
        };
        Relationships: [];
      };
      leads: {
        Row: {
      id: string
      created_at?: string
      full_name: string
      phone?: string
      email?: string
      source?: string
      status?: string
      notes?: string
      expected_value?: number
      hotel_id?: string
        };
        Insert: {
      id: string
      created_at?: string
      full_name: string
      phone?: string
      email?: string
      source?: string
      status?: string
      notes?: string
      expected_value?: number
      hotel_id?: string
        };
        Update: {
      id?: string
      created_at?: string
      full_name?: string
      phone?: string
      email?: string
      source?: string
      status?: string
      notes?: string
      expected_value?: number
      hotel_id?: string
        };
        Relationships: [];
      };
      guests: {
        Row: {
      id: string
      created_at?: string
      full_name: string
      email?: string
      phone?: string
      doc_type?: string
      doc_number?: string
      origin_city?: string
      signature_url?: string
      nationality?: string
      gender?: string
      birth_date?: string
      consent_ip?: string
      consent_user_agent?: string
      consent_timestamp?: string
      hotel_id?: string
      country?: string
      notes?: string
        };
        Insert: {
      id: string
      created_at?: string
      full_name: string
      email?: string
      phone?: string
      doc_type?: string
      doc_number?: string
      origin_city?: string
      signature_url?: string
      nationality?: string
      gender?: string
      birth_date?: string
      consent_ip?: string
      consent_user_agent?: string
      consent_timestamp?: string
      hotel_id?: string
      country?: string
      notes?: string
        };
        Update: {
      id?: string
      created_at?: string
      full_name?: string
      email?: string
      phone?: string
      doc_type?: string
      doc_number?: string
      origin_city?: string
      signature_url?: string
      nationality?: string
      gender?: string
      birth_date?: string
      consent_ip?: string
      consent_user_agent?: string
      consent_timestamp?: string
      hotel_id?: string
      country?: string
      notes?: string
        };
        Relationships: [];
      };
      payment_links: {
        Row: {
      id: string
      created_at?: string
      reservation_id?: string
      amount: number
      status?: string
        };
        Insert: {
      id: string
      created_at?: string
      reservation_id?: string
      amount: number
      status?: string
        };
        Update: {
      id?: string
      created_at?: string
      reservation_id?: string
      amount?: number
      status?: string
        };
        Relationships: [];
      };
      bookings: {
        Row: {
      id: string
      created_at?: string
      hotel_id: string
      room_id?: string
      guest_id?: string
      check_in: string
      check_out: string
      status?: string
      access_token?: string
      total_price?: number
      is_tax_exempt?: boolean
      notes?: string
      source?: string
      ical_import_url?: string
      staff_id?: string
      updated_by?: string
      platform_fee?: number
      referral_channel?: string
        };
        Insert: {
      id: string
      created_at?: string
      hotel_id: string
      room_id?: string
      guest_id?: string
      check_in: string
      check_out: string
      status?: string
      access_token?: string
      total_price?: number
      is_tax_exempt?: boolean
      notes?: string
      source?: string
      ical_import_url?: string
      staff_id?: string
      updated_by?: string
      platform_fee?: number
      referral_channel?: string
        };
        Update: {
      id?: string
      created_at?: string
      hotel_id?: string
      room_id?: string
      guest_id?: string
      check_in?: string
      check_out?: string
      status?: string
      access_token?: string
      total_price?: number
      is_tax_exempt?: boolean
      notes?: string
      source?: string
      ical_import_url?: string
      staff_id?: string
      updated_by?: string
      platform_fee?: number
      referral_channel?: string
        };
        Relationships: [];
      };
      tts_usage: {
        Row: {
      period: string
      neural_count?: number
      wavenet_count?: number
        };
        Insert: {
      period: string
      neural_count?: number
      wavenet_count?: number
        };
        Update: {
      period?: string
      neural_count?: number
      wavenet_count?: number
        };
        Relationships: [];
      };
      staff: {
        Row: {
      id: string
      hotel_id?: string
      name: string
      role: string
      pin_code: string
      created_at?: string
      user_id?: string
        };
        Insert: {
      id: string
      hotel_id?: string
      name: string
      role: string
      pin_code: string
      created_at?: string
      user_id?: string
        };
        Update: {
      id?: string
      hotel_id?: string
      name?: string
      role?: string
      pin_code?: string
      created_at?: string
      user_id?: string
        };
        Relationships: [];
      };
      service_orders: {
        Row: {
      id: number
      hotel_id?: string
      room_id?: string
      guest_name?: string
      items?: Json
      total_price?: number
      status?: string
      created_at?: string
      payment_method?: string
      metadata?: Json
        };
        Insert: {
      id: number
      hotel_id?: string
      room_id?: string
      guest_name?: string
      items?: Json
      total_price?: number
      status?: string
      created_at?: string
      payment_method?: string
      metadata?: Json
        };
        Update: {
      id?: number
      hotel_id?: string
      room_id?: string
      guest_name?: string
      items?: Json
      total_price?: number
      status?: string
      created_at?: string
      payment_method?: string
      metadata?: Json
        };
        Relationships: [];
      };
      menu_items: {
        Row: {
      id: number
      hotel_id?: string
      name: string
      category?: string
      price: number
      description?: string
      image_emoji?: string
      is_active?: boolean
      created_at?: string
      stock: number
        };
        Insert: {
      id: number
      hotel_id?: string
      name: string
      category?: string
      price: number
      description?: string
      image_emoji?: string
      is_active?: boolean
      created_at?: string
      stock: number
        };
        Update: {
      id?: number
      hotel_id?: string
      name?: string
      category?: string
      price?: number
      description?: string
      image_emoji?: string
      is_active?: boolean
      created_at?: string
      stock?: number
        };
        Relationships: [];
      };
      ota_sync_log: {
        Row: {
      id: string
      hotel_id: string
      rooms_synced?: number
      bookings_created?: number
      bookings_cancelled?: number
      bookings_unchanged?: number
      status: string
      error_message?: string
      sync_source?: string
      executed_at?: string
      duration_ms?: number
        };
        Insert: {
      id: string
      hotel_id: string
      rooms_synced?: number
      bookings_created?: number
      bookings_cancelled?: number
      bookings_unchanged?: number
      status: string
      error_message?: string
      sync_source?: string
      executed_at?: string
      duration_ms?: number
        };
        Update: {
      id?: string
      hotel_id?: string
      rooms_synced?: number
      bookings_created?: number
      bookings_cancelled?: number
      bookings_unchanged?: number
      status?: string
      error_message?: string
      sync_source?: string
      executed_at?: string
      duration_ms?: number
        };
        Relationships: [];
      };
      calendar_connections: {
        Row: {
      id: string
      room_id: string
      platform: string
      ical_url: string
      name?: string
      last_sync_at?: string
      sync_status?: string
      error_message?: string
      created_at?: string
      updated_at?: string
        };
        Insert: {
      id: string
      room_id: string
      platform: string
      ical_url: string
      name?: string
      last_sync_at?: string
      sync_status?: string
      error_message?: string
      created_at?: string
      updated_at?: string
        };
        Update: {
      id?: string
      room_id?: string
      platform?: string
      ical_url?: string
      name?: string
      last_sync_at?: string
      sync_status?: string
      error_message?: string
      created_at?: string
      updated_at?: string
        };
        Relationships: [];
      };
      hunted_leads: {
        Row: {
      id: number
      created_at: string
      business_name: string
      google_place_id?: string
      address?: string
      phone?: string
      rating?: number
      website?: string
      ai_pitch?: string
      city_search?: string
      status?: string
      notes?: string
      hotel_id?: string
        };
        Insert: {
      id: number
      created_at: string
      business_name: string
      google_place_id?: string
      address?: string
      phone?: string
      rating?: number
      website?: string
      ai_pitch?: string
      city_search?: string
      status?: string
      notes?: string
      hotel_id?: string
        };
        Update: {
      id?: number
      created_at?: string
      business_name?: string
      google_place_id?: string
      address?: string
      phone?: string
      rating?: number
      website?: string
      ai_pitch?: string
      city_search?: string
      status?: string
      notes?: string
      hotel_id?: string
        };
        Relationships: [];
      };
      saas_subscriptions: {
        Row: {
      id: string
      hotel_id: string
      wompi_payment_source_id?: string
      plan_id?: string
      trial_ends_at: string
      status?: string
        };
        Insert: {
      id: string
      hotel_id: string
      wompi_payment_source_id?: string
      plan_id?: string
      trial_ends_at: string
      status?: string
        };
        Update: {
      id?: string
      hotel_id?: string
      wompi_payment_source_id?: string
      plan_id?: string
      trial_ends_at?: string
      status?: string
        };
        Relationships: [];
      };
      launch_control: {
        Row: {
      id: number
      city_slug: string
      total_spots?: number
      spots_taken?: number
      is_active?: boolean
      created_at?: string
        };
        Insert: {
      id: number
      city_slug: string
      total_spots?: number
      spots_taken?: number
      is_active?: boolean
      created_at?: string
        };
        Update: {
      id?: number
      city_slug?: string
      total_spots?: number
      spots_taken?: number
      is_active?: boolean
      created_at?: string
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
      user_id: string
      role: string
        };
        Insert: {
      user_id: string
      role: string
        };
        Update: {
      user_id?: string
      role?: string
        };
        Relationships: [];
      };
      hotels: {
        Row: {
      id: string
      created_at?: string
      name: string
      slug?: string
      location: string
      plan_tier?: string
      config?: Json
      logo_url?: string
      primary_color?: string
      tax_rate?: number
      payment_qr_url?: string
      phone?: string
      status?: string
      plan_type?: string
      trial_ends_at?: string
      subscription_ends_at?: string
      monthly_price?: number
      email?: string
      city?: string
      settings?: Json
      subscription_plan?: string
      main_image_url?: string
      tagline?: string
      instagram_url?: string
      city_slug?: string
      category?: string
      min_price?: number
      stars?: number
      amenities?: string[]
      owner_id?: string
      wompi_public_key?: string
      wompi_integrity_secret?: string
      commission_rate?: number
      address?: string
      type?: string
      description?: string
      gallery?: string[]
      policies?: Json
      wompi_customer_id?: string
      wompi_payment_source_id?: string
      onboarding_step?: number
      is_onboarding_complete?: boolean
      cover_photo_url?: string
      gallery_urls?: string[]
      hotel_amenities?: Json
      whatsapp_number?: string
      google_maps_url?: string
      cancellation_policy?: string
      show_recent_activity?: boolean
      recent_activity_messages?: Json
      seo_meta_title?: string
      seo_meta_description?: string
      seo_og_image_url?: string
      seo_canonical_url?: string
      category_badge?: string
      show_trust_badges?: boolean
      check_in_time?: string
      check_out_time?: string
      reception_hours?: string
      story_section_title?: string
      trust_badge_1_title?: string
      trust_badge_1_subtitle?: string
      trust_badge_2_title?: string
      trust_badge_2_subtitle?: string
       subscription_status?: string
       billing_cycle_start?: string
       date_paid?: string
       go_live?: boolean
       go_live_at?: string
        };
        Insert: {
      id: string
      created_at?: string
      name: string
      slug?: string
      location: string
      plan_tier?: string
      config?: Json
      logo_url?: string
      primary_color?: string
      tax_rate?: number
      payment_qr_url?: string
      phone?: string
      status?: string
      plan_type?: string
      trial_ends_at?: string
      subscription_ends_at?: string
      monthly_price?: number
      email?: string
      city?: string
      settings?: Json
      subscription_plan?: string
      main_image_url?: string
      tagline?: string
      instagram_url?: string
      city_slug?: string
      category?: string
      min_price?: number
      stars?: number
      amenities?: string[]
      owner_id?: string
      wompi_public_key?: string
      wompi_integrity_secret?: string
      commission_rate?: number
      address?: string
      type?: string
      description?: string
      gallery?: string[]
      policies?: Json
      wompi_customer_id?: string
      wompi_payment_source_id?: string
      onboarding_step?: number
      is_onboarding_complete?: boolean
      cover_photo_url?: string
      gallery_urls?: string[]
      hotel_amenities?: Json
      whatsapp_number?: string
      google_maps_url?: string
      cancellation_policy?: string
      show_recent_activity?: boolean
      recent_activity_messages?: Json
      seo_meta_title?: string
      seo_meta_description?: string
      seo_og_image_url?: string
      seo_canonical_url?: string
      category_badge?: string
      show_trust_badges?: boolean
      check_in_time?: string
      check_out_time?: string
      reception_hours?: string
      story_section_title?: string
      trust_badge_1_title?: string
      trust_badge_1_subtitle?: string
      trust_badge_2_title?: string
      trust_badge_2_subtitle?: string
       subscription_status?: string
       billing_cycle_start?: string
       date_paid?: string
       go_live?: boolean
       go_live_at?: string
        };
        Update: {
      id?: string
      created_at?: string
      name?: string
      slug?: string
      location?: string
      plan_tier?: string
      config?: Json
      logo_url?: string
      primary_color?: string
      tax_rate?: number
      payment_qr_url?: string
      phone?: string
      status?: string
      plan_type?: string
      trial_ends_at?: string
      subscription_ends_at?: string
      monthly_price?: number
      email?: string
      city?: string
      settings?: Json
      subscription_plan?: string
      main_image_url?: string
      tagline?: string
      instagram_url?: string
      city_slug?: string
      category?: string
      min_price?: number
      stars?: number
      amenities?: string[]
      owner_id?: string
      wompi_public_key?: string
      wompi_integrity_secret?: string
      commission_rate?: number
      address?: string
      type?: string
      description?: string
      gallery?: string[]
      policies?: Json
      wompi_customer_id?: string
      wompi_payment_source_id?: string
      onboarding_step?: number
      is_onboarding_complete?: boolean
      cover_photo_url?: string
      gallery_urls?: string[]
      hotel_amenities?: Json
      whatsapp_number?: string
      google_maps_url?: string
      cancellation_policy?: string
      show_recent_activity?: boolean
      recent_activity_messages?: Json
      seo_meta_title?: string
      seo_meta_description?: string
      seo_og_image_url?: string
      seo_canonical_url?: string
      category_badge?: string
      show_trust_badges?: boolean
      check_in_time?: string
      check_out_time?: string
      reception_hours?: string
      story_section_title?: string
      trust_badge_1_title?: string
      trust_badge_1_subtitle?: string
      trust_badge_2_title?: string
      trust_badge_2_subtitle?: string
       subscription_status?: string
       billing_cycle_start?: string
       date_paid?: string
       go_live?: boolean
       go_live_at?: string
        };
        Relationships: [];
      };
      reviews: {
        Row: {
      id: string
      hotel_id: string
      guest_name: string
      guest_email: string
      guest_location?: string
      rating: number
      comment: string
      status: string
      stay_date?: string
      created_at?: string
      updated_at?: string
        };
        Insert: {
      id: string
      hotel_id: string
      guest_name: string
      guest_email: string
      guest_location?: string
      rating: number
      comment: string
      status: string
      stay_date?: string
      created_at?: string
      updated_at?: string
        };
        Update: {
      id?: string
      hotel_id?: string
      guest_name?: string
      guest_email?: string
      guest_location?: string
      rating?: number
      comment?: string
      status?: string
      stay_date?: string
      created_at?: string
      updated_at?: string
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
      id: string
      created_at?: string
      hotel_id?: string
      user_email?: string
      action?: string
      details?: Json
      ip_address?: string
        };
        Insert: {
      id: string
      created_at?: string
      hotel_id?: string
      user_email?: string
      action?: string
      details?: Json
      ip_address?: string
        };
        Update: {
      id?: string
      created_at?: string
      hotel_id?: string
      user_email?: string
      action?: string
      details?: Json
      ip_address?: string
        };
        Relationships: [];
      };
      rooms: {
        Row: {
      id: string
      hotel_id: string
      name: string
      type?: string
      price_base?: number
      status?: string
      price?: number
      base_price?: number
      amenities?: Json
      image_url?: string
      description?: string
      features?: string[]
      capacity?: number
      beds?: number
      bedrooms?: number
      is_price_per_person?: boolean
      images?: string[]
      bed_type?: string
      size?: number
      ical_import_url?: string
      weekend_price?: number
      size_sqm?: number
      gallery?: Json
      ical_export_token: string
      availability_range?: Json
      last_ical_sync?: string
      ical_sync_status?: string
        };
        Insert: {
      id: string
      hotel_id: string
      name: string
      type?: string
      price_base?: number
      status?: string
      price?: number
      base_price?: number
      amenities?: Json
      image_url?: string
      description?: string
      features?: string[]
      capacity?: number
      beds?: number
      bedrooms?: number
      is_price_per_person?: boolean
      images?: string[]
      bed_type?: string
      size?: number
      ical_import_url?: string
      weekend_price?: number
      size_sqm?: number
      gallery?: Json
      ical_export_token: string
      availability_range?: Json
      last_ical_sync?: string
      ical_sync_status?: string
        };
        Update: {
      id?: string
      hotel_id?: string
      name?: string
      type?: string
      price_base?: number
      status?: string
      price?: number
      base_price?: number
      amenities?: Json
      image_url?: string
      description?: string
      features?: string[]
      capacity?: number
      beds?: number
      bedrooms?: number
      is_price_per_person?: boolean
      images?: string[]
      bed_type?: string
      size?: number
      ical_import_url?: string
      weekend_price?: number
      size_sqm?: number
      gallery?: Json
      ical_export_token?: string
      availability_range?: Json
      last_ical_sync?: string
      ical_sync_status?: string
        };
        Relationships: [];
      };
      service_items: {
        Row: {
      id: string
      booking_id?: string
      room_id?: string
      description: string
      total_price: number
      quantity?: number
      status?: string
      created_at: string
        };
        Insert: {
      id: string
      booking_id?: string
      room_id?: string
      description: string
      total_price: number
      quantity?: number
      status?: string
      created_at: string
        };
        Update: {
      id?: string
      booking_id?: string
      room_id?: string
      description?: string
      total_price?: number
      quantity?: number
      status?: string
      created_at?: string
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
